//! END-TO-END WITNESS-BINDING multi-row P256 ECDSA *verification*.
//!
//! Drives the narrow double-scalar-mult kernel (one step/row, K=256
//! rows) PLUS the verify tail (group_add + inverse-free cross-multiply
//! `R.X ≡ {r, r+n}·R.Z (mod p)` + final equality) at row K, and binds
//! the whole thing with `sub_air_with_trace::{prove,verify}`.
//!
//! DECISIVE TEST: a REAL P256 signature (generated by the `p256` crate)
//! ACCEPTS; a tampered one (bogus r, or a corrupted witness cell)
//! REJECTS — and the in-circuit verdict agrees with the native
//! `p256_ecdsa::verify`.  No Fermat inverse → no OOM.
//!
//! Run: cargo run --release -p swarm-dns --example ecdsa_verify_multirow_bound_bench \
//!        --no-default-features --features sha3-256,mldsa-44,parallel

use std::time::Instant;

use ark_ff::{PrimeField, Zero};
use ark_goldilocks::Goldilocks as F;
use sha2::{Digest as _, Sha256};

use p256::ecdsa::{signature::Signer, Signature as P256Signature, SigningKey, VerifyingKey};
use p256::elliptic_curve::sec1::ToEncodedPoint;

use deep_ali::{
    deep_ali_merge_ecdsa_verify_multirow_streaming,
    fri::DeepFriParams,
    p256_ecdsa::{
        reduce_digest_mod_n, verify as ecdsa_verify_native, PublicKey as EcdsaPublicKey,
        Signature as EcdsaSignature,
    },
    p256_ecdsa_verify_multirow_air::{
        build_ecdsa_verify_multirow_layout, ecdsa_verify_multirow_constraints,
        eval_ecdsa_verify_multirow_per_row, fill_ecdsa_verify_multirow,
    },
    p256_field::{FieldElement, NUM_LIMBS},
    p256_group::GENERATOR as P256_GENERATOR,
    p256_scalar::ScalarElement,
    sub_air_with_trace::{prove_one_sub_air_with_trace, verify_one_sub_air_with_trace},
};

const PI_HASH: [u8; 32] = [0x55; 32];

fn scalar_to_msb_bits_256(s: &ScalarElement) -> Vec<bool> {
    let bytes = s.to_be_bytes();
    let mut bits = Vec::with_capacity(256);
    for byte in bytes.iter() {
        for shift in (0..8).rev() {
            bits.push((byte >> shift) & 1 == 1);
        }
    }
    bits
}

fn mk_params(n0: usize, r: usize, use_stir: bool, ph: [u8; 32]) -> DeepFriParams {
    DeepFriParams {
        schedule: (0..n0.trailing_zeros() as usize).map(|_| 2).collect(),
        r, seed_z: 0xDEEFu64, coeff_commit_final: true, d_final: 1,
        stir: use_stir, s0: r, public_inputs_hash: Some(ph),
    }
}

fn read_fe(trace: &[Vec<F>], base: usize, row: usize) -> FieldElement {
    let mut limbs = [0i64; NUM_LIMBS];
    for i in 0..NUM_LIMBS {
        limbs[i] = trace[base + i][row].into_bigint().as_ref()[0] as i64;
    }
    FieldElement { limbs }
}

fn main() {
    let level = deep_ali::stark_level::NIST_LEVEL;
    let ext_deg = deep_ali::permutation_argument::EXT_DEGREE;
    let r = deep_ali::stark_level::NUM_QUERIES_LEVEL;
    let use_stir = matches!(std::env::var("BENCH_LDT").as_deref(), Ok("stir") | Ok("STIR"));
    let blowup = std::env::var("BENCH_BLOWUP").ok().and_then(|s| s.parse().ok()).unwrap_or(4usize);
    let k = std::env::var("KSTEPS").ok().and_then(|s| s.parse().ok()).unwrap_or(256usize);
    let n_trace = (k + 1).next_power_of_two();
    eprintln!("=== ecdsa_verify_multirow_bound_bench: END-TO-END P256 ECDSA verify, \
               K={k}, n_trace={n_trace}, NIST L{level}, Fp{ext_deg}, r={r}, blowup={blowup} ===");

    // ── 1. Real P256 signature (deterministic key) ──
    let sk = SigningKey::from_slice(&[0x42u8; 32]).expect("valid P256 key");
    let msg = b"STARK-DNS END-TO-END ECDSA-P256 verify bench";
    let sig: P256Signature = sk.sign(msg);
    let vk = VerifyingKey::from(&sk);
    let ep = vk.to_encoded_point(false);
    let epb = ep.as_bytes();
    let mut qx = [0u8; 32]; qx.copy_from_slice(&epb[1..33]);
    let mut qy = [0u8; 32]; qy.copy_from_slice(&epb[33..65]);
    let sb = sig.to_bytes();
    let mut rbytes = [0u8; 32]; rbytes.copy_from_slice(&sb[0..32]);
    let mut sbytes = [0u8; 32]; sbytes.copy_from_slice(&sb[32..64]);
    let digest: [u8; 32] = Sha256::digest(msg).into();

    let pk = EcdsaPublicKey::from_be_bytes(&qx, &qy).expect("pk parse");
    let signature = EcdsaSignature::from_be_bytes(&rbytes, &sbytes).expect("sig parse");
    let native_ok = ecdsa_verify_native(&digest, &pk, &signature);
    eprintln!("[native] ecdsa_verify(digest, pk, sig) = {native_ok}");
    assert!(native_ok, "native ECDSA verify must hold for the honest signature");

    // ── 2. u1, u2 (FIPS 186-4 §6.4.2) + MSB bit decompositions ──
    let e = reduce_digest_mod_n(&digest);
    let w = signature.s.invert();
    let u_1 = e.mul(&w);
    let u_2 = signature.r.mul(&w);
    let u1_bits = scalar_to_msb_bits_256(&u_1);
    let u2_bits = scalar_to_msb_bits_256(&u_2);
    assert_eq!(u1_bits.len(), k, "K must be 256 to consume all scalar bits");

    // r as a mod-p field element (r < n < p).
    let r_fe = FieldElement::from_be_bytes(&rbytes);

    // ── 3. Layout + trace ──
    let (layout, total) = build_ecdsa_verify_multirow_layout(0, k);
    let kk = ecdsa_verify_multirow_constraints(&layout);
    eprintln!("    per-row width = {total} cells, constraints = {kk}");

    let g = *P256_GENERATOR;
    let z_one = { let mut t = FieldElement::zero(); t.limbs[0] = 1; t };
    // Projective identity (0:1:0) — the scalar-mult chain start.
    let id_x = FieldElement::zero();
    let id_y = { let mut t = FieldElement::zero(); t.limbs[0] = 1; t };
    let id_z = FieldElement::zero();

    let build_trace = |r_in: &FieldElement| -> Vec<Vec<F>> {
        let mut trace = vec![vec![F::zero(); n_trace]; total];
        fill_ecdsa_verify_multirow(
            &mut trace, &layout, n_trace,
            (&id_x, &id_y, &id_z), (&g.x, &g.y, &z_one), &u1_bits,
            (&id_x, &id_y, &id_z), (&pk.point.x, &pk.point.y, &z_one), &u2_bits,
            r_in,
        );
        trace
    };

    // ── Diagnostic: chain computes the right point? cross-check R.x ──
    {
        let trace = build_trace(&r_fe);
        // Affine x of R from the group_add output at the tail row k.
        let r_x3 = read_fe(&trace, layout.group_add.result_x3_limbs_base, k);
        let r_z3 = read_fe(&trace, layout.group_add.result_z3_limbs_base, k);
        let mut x1 = r_x3.mul(&r_z3.invert());
        x1.freeze();
        // Native R = u1·G + u2·Q.
        let r_native = g.scalar_mul(&u_1).add(&pk.point.scalar_mul(&u_2));
        let mut rx_native = r_native.x;
        rx_native.freeze();
        let agree = x1.ct_eq(&rx_native);
        eprintln!("[diag] in-circuit R.x == native R.x : {agree}");
        // x1 mod n == r ?
        let x1_bytes = x1.to_be_bytes();
        let x1_mod_n = ScalarElement::from_be_bytes(&x1_bytes);
        eprintln!("[diag] (R.x mod n) == sig.r : {}", x1_mod_n.ct_eq(&signature.r));
        assert!(agree, "in-circuit R.x must equal native R.x (chain semantics)");
    }

    let prove_verify = |trace: &[Vec<F>]| -> (f64, f64, usize, bool) {
        let t = Instant::now();
        let proof = prove_one_sub_air_with_trace(
            trace, n_trace, blowup, PI_HASH, b"ecdsa_verify_multirow", kk,
            |lde, nt, bw, cc| deep_ali_merge_ecdsa_verify_multirow_streaming(lde, cc, &layout, nt, bw).0,
            |n0, ph| mk_params(n0, r, use_stir, ph),
        );
        let p_ms = t.elapsed().as_secs_f64() * 1000.0;
        let t = Instant::now();
        let ok = verify_one_sub_air_with_trace(
            &proof, n_trace, blowup, PI_HASH, b"ecdsa_verify_multirow", total, kk,
            |cur, nxt, row| eval_ecdsa_verify_multirow_per_row(cur, nxt, row, n_trace, &layout),
            |n0, ph| mk_params(n0, r, use_stir, ph),
        ).is_ok();
        (p_ms, t.elapsed().as_secs_f64() * 1000.0, proof.fri_proof_bytes.len(), ok)
    };

    // ── Honest: ACCEPT ──
    let honest = build_trace(&r_fe);
    let (p_ms, v_ms, fri_b, ok) = prove_verify(&honest);
    eprintln!("[honest]   prove {p_ms:.1} ms, verify {v_ms:.2} ms, fri {} KiB -> verify={ok}", fri_b / 1024);
    assert!(ok, "BINDING BROKEN: honest END-TO-END ECDSA verify must accept");

    // ── Tampered: corrupt the signature r column at the tail row -> REJECT ──
    let mut bad = honest.clone();
    bad[layout.r_base][k] += F::from(1u64);
    let (_, _, _, bad_ok) = prove_verify(&bad);
    eprintln!("[tampered] perturb r[0] at tail row -> verify={bad_ok}");

    println!(
        "ecdsa_verify_multirow K={k} n_trace={n_trace} per_row_width={total} r={r} blowup={blowup} \
         prove_ms={p_ms:.1} verify_ms={v_ms:.2} fri_kib={} native_verify={native_ok} \
         honest_verify={ok} tampered_verify={bad_ok}",
        fri_b / 1024
    );
    if ok && !bad_ok && native_ok {
        println!("=> END-TO-END WITNESS-BINDING WORKS: real P256 sig accepts, tampered REJECTS, native agrees");
    } else {
        println!("=> FAILED: native={native_ok} honest={ok} tampered={bad_ok}");
    }
}
